resources:
    - name: pratik-instance
      type: compute.v1.instance
      properties: 
        zone: us-central1-a
        machineType: zones/us-central1-a/machineTypes/f1-micro
        disks: 
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autodelete: true
          initializeParams:
            sourceImage: projects/debian-cloud/global/images/family/debian-10
        networkInterfaces:
        - network: global/networks/pratik-vpc
